environment:
  node_pre_gyp_accessKeyId:
    secure: 7DrSVc5eIGtmMcki5H+iRft+Tk3MJTwDBQEUuJHWaQ4=
  node_pre_gyp_secretAccessKey:
    secure: 1amwJJw9fu0j6dXnc5KsAQbSYf7Cjw/dapT6OZWABa6nc52grkKeLQ+DGaOfQz8i
  matrix:
    - nodejs_version: 4
      platform: x64
    - nodejs_version: 4
      platform: x86
    - nodejs_version: 5
      platform: x64
    - nodejs_version: 5
      platform: x86
    - nodejs_version: 6
      platform: x64
    - nodejs_version: 6
      platform: x86
    - nodejs_version: 7
      platform: x64
    - nodejs_version: 7
      platform: x86
    - nodejs_version: 8
      platform: x64
    - nodejs_version: 8
      platform: x86
    - nodejs_version: 9
      platform: x64
    - nodejs_version: 9
      platform: x86

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
