version: 1
files:
  - filename: cibc.json
    search: cibc
    historyfill: No
  - filename: bmo.json
    search: BMO
    historyfill: No
  - filename: scotia.json
    search: scotiabank
    historyfill: No
  - filename: national.json
    search: nationalbank
    historyfill: No
  - filename: rbc.json
    search: RBC
    historyfill: No
  - filename: td.json
    search: TD_Canada
    historyfill: No
  - filename: laurentian.json
    search: laurentian_b
    historyfill: Yes
  - filename: laurentienne.json
    search: BLaurentienne
    historyfill: Yes
  - filename: desjardins.json
    search: DesjardinsCoop
    historyfill: Yes
  - filename: desjardinsgroup.json
    search: DesjardinsGroup
    historyfill: Yes
  - filename: transat.json
    search: airtransat
    historyfill: Yes
  - filename: ac.json
    search: AirCanada
    historyfill: No
  - filename: rouge.json
    search: AirCanadaRouge
    historyfill: Yes
  - filename: acvac.json
    search: AirCanadaVac
    historyfill: Yes
  - filename: westjet.json
    search: WestJet
    historyfill: Yes
  - filename: swoop.json
    search: FlySwoop
    historyfill: Yes
  - filename: sunwingv.json
    search: SunwingVacay
    historyfill: Yes
  - filename: sunwing.json
    search: sunwing
    historyfill: Yes
  - filename: flair.json
    search: FlairAirlines
    historyfill: Yes
  - filename: owg.json
    search: owgvoyages
    historyfill: Yes
  - filename: lynx.json
    search: Lynx_Air
    historyfill: Yes
  - filename: jetlines.json
    search: CA_Jetlines
    historyfill: Yes
